language: java

build: trusty

jdk:
- oraclejdk8

git:
  quiet: true

before_script:
- wget https://chromedriver.storage.googleapis.com/2.44/chromedriver_linux64.zip
- wget https://drive.google.com/open?id=1jSnhkHdQX2NgaPgJOlQ8bv0RIHW-PAZM
- unzip chromedriver_linux64.zip 


addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install: true

script: 
- mvn clean install -U
- mvn dependency::tree
- mvn clean test
- mvn -f pom.xml test


after_failure:
- cat target/surefire-reports/*.txt
